version: '2.2'

services:

  db-node-1:
    build:
      context: mysql
      dockerfile: Dockerfile
    container_name: db-node-1
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: archdb
      MYSQL_USER: stud
      MYSQL_PASSWORD: stud
      MYSQL_ROOT_PASSWORD: '1'
    # command: >
    #   --sql-mode='STRICT_TRANS_TABLES,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION'
    #   --general-log=ON
    #   --log-queries-not-using-indexes=ON
    networks:
      - arch-network
    ports:
      - 3360:3306
    volumes:
      - db-node-1-data:/var/lib/mysql

  db-node-2:
    build:
      context: mysql
      dockerfile: Dockerfile
    container_name: db-node-2
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: archdb
      MYSQL_USER: stud
      MYSQL_PASSWORD: stud
      MYSQL_ROOT_PASSWORD: '1'
    networks:
      - arch-network
    ports:
      - 3361:3306
    volumes:
      - db-node-2-data:/var/lib/mysql

  db-node-3:
    build:
      context: mysql
      dockerfile: Dockerfile
    container_name: db-node-3
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: archdb
      MYSQL_USER: stud
      MYSQL_PASSWORD: stud
      MYSQL_ROOT_PASSWORD: '1'
    networks:
      - arch-network
    ports:
      - 3362:3306
    volumes:
      - db-node-3-data:/var/lib/mysql

      
  proxysql:
    build:
      context: proxysql
      dockerfile: Dockerfile
    container_name: proxysql
    command: >
      --initial
    volumes:
      - proxysql-data:/var/lib/proxysql
    healthcheck:
      test: "/usr/bin/mysql --user=stud --password=stud --execute \"SHOW DATABASES;\""
      timeout: 20s
      retries: 5
    networks:
      - arch-network
    ports:
      # Mysql Client Port
      - "6033:6033"
      # Mysql Admin Port
      - "6032:6032"
    depends_on:
      - db-node-1
      - db-node-2
      - db-node-3

  # mai-db-node-ex01:
  #   build:
  #     context: mariadb
  #     dockerfile: Dockerfile
  #   container_name: mai-db-node-ex01
  #   restart: unless-stopped
  #   environment:
  #     MYSQL_DATABASE: archdb
  #     MYSQL_USER: stud
  #     MYSQL_PASSWORD: stud
  #     MYSQL_ROOT_PASSWORD: '1'
  #   command: >
  #     --sql-mode='STRICT_TRANS_TABLES,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION'
  #     --general-log=ON
  #     --log-queries-not-using-indexes=ON
  #   networks:
  #     - arch-network
  #   ports:
  #     - 3360:3306
  #   healthcheck:
  #     test: "/usr/bin/mariadb --user=stud --password=stud --execute \"SHOW DATABASES;\""
  #     interval: 15s
  #     timeout: 1s
  #     retries: 5
  #   volumes:
  #     - db-node-ex01-data:/var/lib/mysql

  service_user:
    build:
      context: service_user
      dockerfile: Dockerfile
    container_name: service_user
    environment:
      - DB_HOST=proxysql
      - DB_PORT=6033
      - DB_LOGIN=stud
      - DB_PASSWORD=stud
      - DB_DATABASE=archdb
    ports:
      - 8080:8080
    networks:
      - arch-network
    depends_on:
      - proxysql

  service_good:
    build:
      context: service_good
      dockerfile: Dockerfile
    container_name: service_good
    environment:
      - DB_HOST=proxysql
      - DB_PORT=6033
      - DB_LOGIN=stud
      - DB_PASSWORD=stud
      - DB_DATABASE=archdb
    ports:
      - 8081:8081
    networks:
      - arch-network
    depends_on:
      - proxysql

  service_cart:
    build:
      context: service_cart
      dockerfile: Dockerfile
    container_name: service_cart
    environment:
      - DB_HOST=proxysql
      - DB_PORT=6033
      - DB_LOGIN=stud
      - DB_PASSWORD=stud
      - DB_DATABASE=archdb
    ports:
      - 8082:8082
    networks:
      - arch-network
    depends_on:
      - proxysql


volumes:
  db-node-1-data:
  db-node-2-data:
  db-node-3-data:
  proxysql-data:

networks:
  arch-network:
    driver: "bridge"
    external: false